// This is autogenerated from the generate:errors script, do not edit manually.

export interface ProtocolErrorDefinition {
  id: string
  code: number
  canRetry: boolean
  message: string
}

export const protocolErrorsCodesById: Record<number, string> = {
  0: 'NONE',
  1: 'OFFSET_OUT_OF_RANGE',
  2: 'CORRUPT_MESSAGE',
  3: 'UNKNOWN_TOPIC_OR_PARTITION',
  4: 'INVALID_FETCH_SIZE',
  5: 'LEADER_NOT_AVAILABLE',
  6: 'NOT_LEADER_OR_FOLLOWER',
  7: 'REQUEST_TIMED_OUT',
  8: 'BROKER_NOT_AVAILABLE',
  9: 'REPLICA_NOT_AVAILABLE',
  10: 'MESSAGE_TOO_LARGE',
  11: 'STALE_CONTROLLER_EPOCH',
  12: 'OFFSET_METADATA_TOO_LARGE',
  13: 'NETWORK_EXCEPTION',
  14: 'COORDINATOR_LOAD_IN_PROGRESS',
  15: 'COORDINATOR_NOT_AVAILABLE',
  16: 'NOT_COORDINATOR',
  17: 'INVALID_TOPIC_EXCEPTION',
  18: 'RECORD_LIST_TOO_LARGE',
  19: 'NOT_ENOUGH_REPLICAS',
  20: 'NOT_ENOUGH_REPLICAS_AFTER_APPEND',
  21: 'INVALID_REQUIRED_ACKS',
  22: 'ILLEGAL_GENERATION',
  23: 'INCONSISTENT_GROUP_PROTOCOL',
  24: 'INVALID_GROUP_ID',
  25: 'UNKNOWN_MEMBER_ID',
  26: 'INVALID_SESSION_TIMEOUT',
  27: 'REBALANCE_IN_PROGRESS',
  28: 'INVALID_COMMIT_OFFSET_SIZE',
  29: 'TOPIC_AUTHORIZATION_FAILED',
  30: 'GROUP_AUTHORIZATION_FAILED',
  31: 'CLUSTER_AUTHORIZATION_FAILED',
  32: 'INVALID_TIMESTAMP',
  33: 'UNSUPPORTED_SASL_MECHANISM',
  34: 'ILLEGAL_SASL_STATE',
  35: 'UNSUPPORTED_VERSION',
  36: 'TOPIC_ALREADY_EXISTS',
  37: 'INVALID_PARTITIONS',
  38: 'INVALID_REPLICATION_FACTOR',
  39: 'INVALID_REPLICA_ASSIGNMENT',
  40: 'INVALID_CONFIG',
  41: 'NOT_CONTROLLER',
  42: 'INVALID_REQUEST',
  43: 'UNSUPPORTED_FOR_MESSAGE_FORMAT',
  44: 'POLICY_VIOLATION',
  45: 'OUT_OF_ORDER_SEQUENCE_NUMBER',
  46: 'DUPLICATE_SEQUENCE_NUMBER',
  47: 'INVALID_PRODUCER_EPOCH',
  48: 'INVALID_TXN_STATE',
  49: 'INVALID_PRODUCER_ID_MAPPING',
  50: 'INVALID_TRANSACTION_TIMEOUT',
  51: 'CONCURRENT_TRANSACTIONS',
  52: 'TRANSACTION_COORDINATOR_FENCED',
  53: 'TRANSACTIONAL_ID_AUTHORIZATION_FAILED',
  54: 'SECURITY_DISABLED',
  55: 'OPERATION_NOT_ATTEMPTED',
  56: 'KAFKA_STORAGE_ERROR',
  57: 'LOG_DIR_NOT_FOUND',
  58: 'SASL_AUTHENTICATION_FAILED',
  59: 'UNKNOWN_PRODUCER_ID',
  60: 'REASSIGNMENT_IN_PROGRESS',
  61: 'DELEGATION_TOKEN_AUTH_DISABLED',
  62: 'DELEGATION_TOKEN_NOT_FOUND',
  63: 'DELEGATION_TOKEN_OWNER_MISMATCH',
  64: 'DELEGATION_TOKEN_REQUEST_NOT_ALLOWED',
  65: 'DELEGATION_TOKEN_AUTHORIZATION_FAILED',
  66: 'DELEGATION_TOKEN_EXPIRED',
  67: 'INVALID_PRINCIPAL_TYPE',
  68: 'NON_EMPTY_GROUP',
  69: 'GROUP_ID_NOT_FOUND',
  70: 'FETCH_SESSION_ID_NOT_FOUND',
  71: 'INVALID_FETCH_SESSION_EPOCH',
  72: 'LISTENER_NOT_FOUND',
  73: 'TOPIC_DELETION_DISABLED',
  74: 'FENCED_LEADER_EPOCH',
  75: 'UNKNOWN_LEADER_EPOCH',
  76: 'UNSUPPORTED_COMPRESSION_TYPE',
  77: 'STALE_BROKER_EPOCH',
  78: 'OFFSET_NOT_AVAILABLE',
  79: 'MEMBER_ID_REQUIRED',
  80: 'PREFERRED_LEADER_NOT_AVAILABLE',
  81: 'GROUP_MAX_SIZE_REACHED',
  82: 'FENCED_INSTANCE_ID',
  83: 'ELIGIBLE_LEADERS_NOT_AVAILABLE',
  84: 'ELECTION_NOT_NEEDED',
  85: 'NO_REASSIGNMENT_IN_PROGRESS',
  86: 'GROUP_SUBSCRIBED_TO_TOPIC',
  87: 'INVALID_RECORD',
  88: 'UNSTABLE_OFFSET_COMMIT',
  89: 'THROTTLING_QUOTA_EXCEEDED',
  90: 'PRODUCER_FENCED',
  91: 'RESOURCE_NOT_FOUND',
  92: 'DUPLICATE_RESOURCE',
  93: 'UNACCEPTABLE_CREDENTIAL',
  94: 'INCONSISTENT_VOTER_SET',
  95: 'INVALID_UPDATE_VERSION',
  96: 'FEATURE_UPDATE_FAILED',
  97: 'PRINCIPAL_DESERIALIZATION_FAILURE',
  98: 'SNAPSHOT_NOT_FOUND',
  99: 'POSITION_OUT_OF_RANGE',
  100: 'UNKNOWN_TOPIC_ID',
  101: 'DUPLICATE_BROKER_REGISTRATION',
  102: 'BROKER_ID_NOT_REGISTERED',
  103: 'INCONSISTENT_TOPIC_ID',
  104: 'INCONSISTENT_CLUSTER_ID',
  105: 'TRANSACTIONAL_ID_NOT_FOUND',
  106: 'FETCH_SESSION_TOPIC_ID_ERROR',
  107: 'INELIGIBLE_REPLICA',
  108: 'NEW_LEADER_ELECTED',
  109: 'OFFSET_MOVED_TO_TIERED_STORAGE',
  110: 'FENCED_MEMBER_EPOCH',
  111: 'UNRELEASED_INSTANCE_ID',
  112: 'UNSUPPORTED_ASSIGNOR',
  113: 'STALE_MEMBER_EPOCH',
  114: 'MISMATCHED_ENDPOINT_TYPE',
  115: 'UNSUPPORTED_ENDPOINT_TYPE',
  116: 'UNKNOWN_CONTROLLER_ID',
  117: 'UNKNOWN_SUBSCRIPTION_ID',
  118: 'TELEMETRY_TOO_LARGE',
  119: 'INVALID_REGISTRATION',
  120: 'TRANSACTION_ABORTABLE',
  121: 'INVALID_RECORD_STATE',
  122: 'SHARE_SESSION_NOT_FOUND',
  123: 'INVALID_SHARE_SESSION_EPOCH',
  124: 'FENCED_STATE_EPOCH',
  125: 'INVALID_VOTER_KEY',
  126: 'DUPLICATE_VOTER',
  127: 'VOTER_NOT_FOUND',
  '-1': 'UNKNOWN_SERVER_ERROR'
}

export const protocolErrors: Record<string, ProtocolErrorDefinition> = {
  UNKNOWN_SERVER_ERROR: {
    id: 'UNKNOWN_SERVER_ERROR',
    code: -1,
    canRetry: false,
    message: 'The server experienced an unexpected error when processing the request.'
  },
  NONE: {
    id: 'NONE',
    code: 0,
    canRetry: false,
    message: ''
  },
  OFFSET_OUT_OF_RANGE: {
    id: 'OFFSET_OUT_OF_RANGE',
    code: 1,
    canRetry: false,
    message: 'The requested offset is not within the range of offsets maintained by the server.'
  },
  CORRUPT_MESSAGE: {
    id: 'CORRUPT_MESSAGE',
    code: 2,
    canRetry: true,
    message:
      'This message has failed its CRC checksum, exceeds the valid size, has a null key for a compacted topic, or is otherwise corrupt.'
  },
  UNKNOWN_TOPIC_OR_PARTITION: {
    id: 'UNKNOWN_TOPIC_OR_PARTITION',
    code: 3,
    canRetry: true,
    message: 'This server does not host this topic-partition.'
  },
  INVALID_FETCH_SIZE: {
    id: 'INVALID_FETCH_SIZE',
    code: 4,
    canRetry: false,
    message: 'The requested fetch size is invalid.'
  },
  LEADER_NOT_AVAILABLE: {
    id: 'LEADER_NOT_AVAILABLE',
    code: 5,
    canRetry: true,
    message: 'There is no leader for this topic-partition as we are in the middle of a leadership election.'
  },
  NOT_LEADER_OR_FOLLOWER: {
    id: 'NOT_LEADER_OR_FOLLOWER',
    code: 6,
    canRetry: true,
    message:
      'For requests intended only for the leader, this error indicates that the broker is not the current leader. For requests intended for any replica, this error indicates that the broker is not a replica of the topic partition.'
  },
  REQUEST_TIMED_OUT: {
    id: 'REQUEST_TIMED_OUT',
    code: 7,
    canRetry: true,
    message: 'The request timed out.'
  },
  BROKER_NOT_AVAILABLE: {
    id: 'BROKER_NOT_AVAILABLE',
    code: 8,
    canRetry: false,
    message: 'The broker is not available.'
  },
  REPLICA_NOT_AVAILABLE: {
    id: 'REPLICA_NOT_AVAILABLE',
    code: 9,
    canRetry: true,
    message:
      'The replica is not available for the requested topic-partition. Produce/Fetch requests and other requests intended only for the leader or follower return NOT_LEADER_OR_FOLLOWER if the broker is not a replica of the topic-partition.'
  },
  MESSAGE_TOO_LARGE: {
    id: 'MESSAGE_TOO_LARGE',
    code: 10,
    canRetry: false,
    message: 'The request included a message larger than the max message size the server will accept.'
  },
  STALE_CONTROLLER_EPOCH: {
    id: 'STALE_CONTROLLER_EPOCH',
    code: 11,
    canRetry: false,
    message: 'The controller moved to another broker.'
  },
  OFFSET_METADATA_TOO_LARGE: {
    id: 'OFFSET_METADATA_TOO_LARGE',
    code: 12,
    canRetry: false,
    message: 'The metadata field of the offset request was too large.'
  },
  NETWORK_EXCEPTION: {
    id: 'NETWORK_EXCEPTION',
    code: 13,
    canRetry: true,
    message: 'The server disconnected before a response was received.'
  },
  COORDINATOR_LOAD_IN_PROGRESS: {
    id: 'COORDINATOR_LOAD_IN_PROGRESS',
    code: 14,
    canRetry: true,
    message: "The coordinator is loading and hence can't process requests."
  },
  COORDINATOR_NOT_AVAILABLE: {
    id: 'COORDINATOR_NOT_AVAILABLE',
    code: 15,
    canRetry: true,
    message: 'The coordinator is not available.'
  },
  NOT_COORDINATOR: {
    id: 'NOT_COORDINATOR',
    code: 16,
    canRetry: true,
    message: 'This is not the correct coordinator.'
  },
  INVALID_TOPIC_EXCEPTION: {
    id: 'INVALID_TOPIC_EXCEPTION',
    code: 17,
    canRetry: false,
    message: 'The request attempted to perform an operation on an invalid topic.'
  },
  RECORD_LIST_TOO_LARGE: {
    id: 'RECORD_LIST_TOO_LARGE',
    code: 18,
    canRetry: false,
    message: 'The request included message batch larger than the configured segment size on the server.'
  },
  NOT_ENOUGH_REPLICAS: {
    id: 'NOT_ENOUGH_REPLICAS',
    code: 19,
    canRetry: true,
    message: 'Messages are rejected since there are fewer in-sync replicas than required.'
  },
  NOT_ENOUGH_REPLICAS_AFTER_APPEND: {
    id: 'NOT_ENOUGH_REPLICAS_AFTER_APPEND',
    code: 20,
    canRetry: true,
    message: 'Messages are written to the log, but to fewer in-sync replicas than required.'
  },
  INVALID_REQUIRED_ACKS: {
    id: 'INVALID_REQUIRED_ACKS',
    code: 21,
    canRetry: false,
    message: 'Produce request specified an invalid value for required acks.'
  },
  ILLEGAL_GENERATION: {
    id: 'ILLEGAL_GENERATION',
    code: 22,
    canRetry: false,
    message: 'Specified group generation id is not valid.'
  },
  INCONSISTENT_GROUP_PROTOCOL: {
    id: 'INCONSISTENT_GROUP_PROTOCOL',
    code: 23,
    canRetry: false,
    message:
      "The group member's supported protocols are incompatible with those of existing members or first group member tried to join with empty protocol type or empty protocol list."
  },
  INVALID_GROUP_ID: {
    id: 'INVALID_GROUP_ID',
    code: 24,
    canRetry: false,
    message: 'The configured groupId is invalid.'
  },
  UNKNOWN_MEMBER_ID: {
    id: 'UNKNOWN_MEMBER_ID',
    code: 25,
    canRetry: false,
    message: 'The coordinator is not aware of this member.'
  },
  INVALID_SESSION_TIMEOUT: {
    id: 'INVALID_SESSION_TIMEOUT',
    code: 26,
    canRetry: false,
    message:
      'The session timeout is not within the range allowed by the broker (as configured by group.min.session.timeout.ms and group.max.session.timeout.ms).'
  },
  REBALANCE_IN_PROGRESS: {
    id: 'REBALANCE_IN_PROGRESS',
    code: 27,
    canRetry: false,
    message: 'The group is rebalancing, so a rejoin is needed.'
  },
  INVALID_COMMIT_OFFSET_SIZE: {
    id: 'INVALID_COMMIT_OFFSET_SIZE',
    code: 28,
    canRetry: false,
    message: 'The committing offset data size is not valid.'
  },
  TOPIC_AUTHORIZATION_FAILED: {
    id: 'TOPIC_AUTHORIZATION_FAILED',
    code: 29,
    canRetry: false,
    message: 'Topic authorization failed.'
  },
  GROUP_AUTHORIZATION_FAILED: {
    id: 'GROUP_AUTHORIZATION_FAILED',
    code: 30,
    canRetry: false,
    message: 'Group authorization failed.'
  },
  CLUSTER_AUTHORIZATION_FAILED: {
    id: 'CLUSTER_AUTHORIZATION_FAILED',
    code: 31,
    canRetry: false,
    message: 'Cluster authorization failed.'
  },
  INVALID_TIMESTAMP: {
    id: 'INVALID_TIMESTAMP',
    code: 32,
    canRetry: false,
    message: 'The timestamp of the message is out of acceptable range.'
  },
  UNSUPPORTED_SASL_MECHANISM: {
    id: 'UNSUPPORTED_SASL_MECHANISM',
    code: 33,
    canRetry: false,
    message: 'The broker does not support the requested SASL mechanism.'
  },
  ILLEGAL_SASL_STATE: {
    id: 'ILLEGAL_SASL_STATE',
    code: 34,
    canRetry: false,
    message: 'Request is not valid given the current SASL state.'
  },
  UNSUPPORTED_VERSION: {
    id: 'UNSUPPORTED_VERSION',
    code: 35,
    canRetry: false,
    message: 'The version of API is not supported.'
  },
  TOPIC_ALREADY_EXISTS: {
    id: 'TOPIC_ALREADY_EXISTS',
    code: 36,
    canRetry: false,
    message: 'Topic with this name already exists.'
  },
  INVALID_PARTITIONS: {
    id: 'INVALID_PARTITIONS',
    code: 37,
    canRetry: false,
    message: 'Number of partitions is below 1.'
  },
  INVALID_REPLICATION_FACTOR: {
    id: 'INVALID_REPLICATION_FACTOR',
    code: 38,
    canRetry: false,
    message: 'Replication factor is below 1 or larger than the number of available brokers.'
  },
  INVALID_REPLICA_ASSIGNMENT: {
    id: 'INVALID_REPLICA_ASSIGNMENT',
    code: 39,
    canRetry: false,
    message: 'Replica assignment is invalid.'
  },
  INVALID_CONFIG: {
    id: 'INVALID_CONFIG',
    code: 40,
    canRetry: false,
    message: 'Configuration is invalid.'
  },
  NOT_CONTROLLER: {
    id: 'NOT_CONTROLLER',
    code: 41,
    canRetry: true,
    message: 'This is not the correct controller for this cluster.'
  },
  INVALID_REQUEST: {
    id: 'INVALID_REQUEST',
    code: 42,
    canRetry: false,
    message:
      'This most likely occurs because of a request being malformed by the client library or the message was sent to an incompatible broker. See the broker logs for more details.'
  },
  UNSUPPORTED_FOR_MESSAGE_FORMAT: {
    id: 'UNSUPPORTED_FOR_MESSAGE_FORMAT',
    code: 43,
    canRetry: false,
    message: 'The message format version on the broker does not support the request.'
  },
  POLICY_VIOLATION: {
    id: 'POLICY_VIOLATION',
    code: 44,
    canRetry: false,
    message: 'Request parameters do not satisfy the configured policy.'
  },
  OUT_OF_ORDER_SEQUENCE_NUMBER: {
    id: 'OUT_OF_ORDER_SEQUENCE_NUMBER',
    code: 45,
    canRetry: false,
    message: 'The broker received an out of order sequence number.'
  },
  DUPLICATE_SEQUENCE_NUMBER: {
    id: 'DUPLICATE_SEQUENCE_NUMBER',
    code: 46,
    canRetry: false,
    message: 'The broker received a duplicate sequence number.'
  },
  INVALID_PRODUCER_EPOCH: {
    id: 'INVALID_PRODUCER_EPOCH',
    code: 47,
    canRetry: false,
    message: 'Producer attempted to produce with an old epoch.'
  },
  INVALID_TXN_STATE: {
    id: 'INVALID_TXN_STATE',
    code: 48,
    canRetry: false,
    message: 'The producer attempted a transactional operation in an invalid state.'
  },
  INVALID_PRODUCER_ID_MAPPING: {
    id: 'INVALID_PRODUCER_ID_MAPPING',
    code: 49,
    canRetry: false,
    message: 'The producer attempted to use a producer id which is not currently assigned to its transactional id.'
  },
  INVALID_TRANSACTION_TIMEOUT: {
    id: 'INVALID_TRANSACTION_TIMEOUT',
    code: 50,
    canRetry: false,
    message:
      'The transaction timeout is larger than the maximum value allowed by the broker (as configured by transaction.max.timeout.ms).'
  },
  CONCURRENT_TRANSACTIONS: {
    id: 'CONCURRENT_TRANSACTIONS',
    code: 51,
    canRetry: true,
    message:
      'The producer attempted to update a transaction while another concurrent operation on the same transaction was ongoing.'
  },
  TRANSACTION_COORDINATOR_FENCED: {
    id: 'TRANSACTION_COORDINATOR_FENCED',
    code: 52,
    canRetry: false,
    message:
      'Indicates that the transaction coordinator sending a WriteTxnMarker is no longer the current coordinator for a given producer.'
  },
  TRANSACTIONAL_ID_AUTHORIZATION_FAILED: {
    id: 'TRANSACTIONAL_ID_AUTHORIZATION_FAILED',
    code: 53,
    canRetry: false,
    message: 'Transactional Id authorization failed.'
  },
  SECURITY_DISABLED: {
    id: 'SECURITY_DISABLED',
    code: 54,
    canRetry: false,
    message: 'Security features are disabled.'
  },
  OPERATION_NOT_ATTEMPTED: {
    id: 'OPERATION_NOT_ATTEMPTED',
    code: 55,
    canRetry: false,
    message:
      'The broker did not attempt to execute this operation. This may happen for batched RPCs where some operations in the batch failed, causing the broker to respond without trying the rest.'
  },
  KAFKA_STORAGE_ERROR: {
    id: 'KAFKA_STORAGE_ERROR',
    code: 56,
    canRetry: true,
    message: 'Disk error when trying to access log file on the disk.'
  },
  LOG_DIR_NOT_FOUND: {
    id: 'LOG_DIR_NOT_FOUND',
    code: 57,
    canRetry: false,
    message: 'The user-specified log directory is not found in the broker config.'
  },
  SASL_AUTHENTICATION_FAILED: {
    id: 'SASL_AUTHENTICATION_FAILED',
    code: 58,
    canRetry: false,
    message: 'SASL authentication failed.'
  },
  UNKNOWN_PRODUCER_ID: {
    id: 'UNKNOWN_PRODUCER_ID',
    code: 59,
    canRetry: false,
    message:
      "This exception is raised by the broker if it could not locate the producer metadata associated with the producerId in question. This could happen if, for instance, the producer's records were deleted because their retention time had elapsed. Once the last records of the producerId are removed, the producer's metadata is removed from the broker, and future appends by the producer will return this exception."
  },
  REASSIGNMENT_IN_PROGRESS: {
    id: 'REASSIGNMENT_IN_PROGRESS',
    code: 60,
    canRetry: false,
    message: 'A partition reassignment is in progress.'
  },
  DELEGATION_TOKEN_AUTH_DISABLED: {
    id: 'DELEGATION_TOKEN_AUTH_DISABLED',
    code: 61,
    canRetry: false,
    message: 'Delegation Token feature is not enabled.'
  },
  DELEGATION_TOKEN_NOT_FOUND: {
    id: 'DELEGATION_TOKEN_NOT_FOUND',
    code: 62,
    canRetry: false,
    message: 'Delegation Token is not found on server.'
  },
  DELEGATION_TOKEN_OWNER_MISMATCH: {
    id: 'DELEGATION_TOKEN_OWNER_MISMATCH',
    code: 63,
    canRetry: false,
    message: 'Specified Principal is not valid Owner/Renewer.'
  },
  DELEGATION_TOKEN_REQUEST_NOT_ALLOWED: {
    id: 'DELEGATION_TOKEN_REQUEST_NOT_ALLOWED',
    code: 64,
    canRetry: false,
    message:
      'Delegation Token requests are not allowed on PLAINTEXT/1-way SSL channels and on delegation token authenticated channels.'
  },
  DELEGATION_TOKEN_AUTHORIZATION_FAILED: {
    id: 'DELEGATION_TOKEN_AUTHORIZATION_FAILED',
    code: 65,
    canRetry: false,
    message: 'Delegation Token authorization failed.'
  },
  DELEGATION_TOKEN_EXPIRED: {
    id: 'DELEGATION_TOKEN_EXPIRED',
    code: 66,
    canRetry: false,
    message: 'Delegation Token is expired.'
  },
  INVALID_PRINCIPAL_TYPE: {
    id: 'INVALID_PRINCIPAL_TYPE',
    code: 67,
    canRetry: false,
    message: 'Supplied principalType is not supported.'
  },
  NON_EMPTY_GROUP: {
    id: 'NON_EMPTY_GROUP',
    code: 68,
    canRetry: false,
    message: 'The group is not empty.'
  },
  GROUP_ID_NOT_FOUND: {
    id: 'GROUP_ID_NOT_FOUND',
    code: 69,
    canRetry: false,
    message: 'The group id does not exist.'
  },
  FETCH_SESSION_ID_NOT_FOUND: {
    id: 'FETCH_SESSION_ID_NOT_FOUND',
    code: 70,
    canRetry: true,
    message: 'The fetch session ID was not found.'
  },
  INVALID_FETCH_SESSION_EPOCH: {
    id: 'INVALID_FETCH_SESSION_EPOCH',
    code: 71,
    canRetry: true,
    message: 'The fetch session epoch is invalid.'
  },
  LISTENER_NOT_FOUND: {
    id: 'LISTENER_NOT_FOUND',
    code: 72,
    canRetry: true,
    message:
      'There is no listener on the leader broker that matches the listener on which metadata request was processed.'
  },
  TOPIC_DELETION_DISABLED: {
    id: 'TOPIC_DELETION_DISABLED',
    code: 73,
    canRetry: false,
    message: 'Topic deletion is disabled.'
  },
  FENCED_LEADER_EPOCH: {
    id: 'FENCED_LEADER_EPOCH',
    code: 74,
    canRetry: true,
    message: 'The leader epoch in the request is older than the epoch on the broker.'
  },
  UNKNOWN_LEADER_EPOCH: {
    id: 'UNKNOWN_LEADER_EPOCH',
    code: 75,
    canRetry: true,
    message: 'The leader epoch in the request is newer than the epoch on the broker.'
  },
  UNSUPPORTED_COMPRESSION_TYPE: {
    id: 'UNSUPPORTED_COMPRESSION_TYPE',
    code: 76,
    canRetry: false,
    message: 'The requesting client does not support the compression type of given partition.'
  },
  STALE_BROKER_EPOCH: {
    id: 'STALE_BROKER_EPOCH',
    code: 77,
    canRetry: false,
    message: 'Broker epoch has changed.'
  },
  OFFSET_NOT_AVAILABLE: {
    id: 'OFFSET_NOT_AVAILABLE',
    code: 78,
    canRetry: true,
    message:
      'The leader high watermark has not caught up from a recent leader election so the offsets cannot be guaranteed to be monotonically increasing.'
  },
  MEMBER_ID_REQUIRED: {
    id: 'MEMBER_ID_REQUIRED',
    code: 79,
    canRetry: false,
    message: 'The group member needs to have a valid member id before actually entering a consumer group.'
  },
  PREFERRED_LEADER_NOT_AVAILABLE: {
    id: 'PREFERRED_LEADER_NOT_AVAILABLE',
    code: 80,
    canRetry: true,
    message: 'The preferred leader was not available.'
  },
  GROUP_MAX_SIZE_REACHED: {
    id: 'GROUP_MAX_SIZE_REACHED',
    code: 81,
    canRetry: false,
    message: 'The consumer group has reached its max size.'
  },
  FENCED_INSTANCE_ID: {
    id: 'FENCED_INSTANCE_ID',
    code: 82,
    canRetry: false,
    message:
      'The broker rejected this static consumer since another consumer with the same group.instance.id has registered with a different member.id.'
  },
  ELIGIBLE_LEADERS_NOT_AVAILABLE: {
    id: 'ELIGIBLE_LEADERS_NOT_AVAILABLE',
    code: 83,
    canRetry: true,
    message: 'Eligible topic partition leaders are not available.'
  },
  ELECTION_NOT_NEEDED: {
    id: 'ELECTION_NOT_NEEDED',
    code: 84,
    canRetry: true,
    message: 'Leader election not needed for topic partition.'
  },
  NO_REASSIGNMENT_IN_PROGRESS: {
    id: 'NO_REASSIGNMENT_IN_PROGRESS',
    code: 85,
    canRetry: false,
    message: 'No partition reassignment is in progress.'
  },
  GROUP_SUBSCRIBED_TO_TOPIC: {
    id: 'GROUP_SUBSCRIBED_TO_TOPIC',
    code: 86,
    canRetry: false,
    message: 'Deleting offsets of a topic is forbidden while the consumer group is actively subscribed to it.'
  },
  INVALID_RECORD: {
    id: 'INVALID_RECORD',
    code: 87,
    canRetry: false,
    message: 'This record has failed the validation on broker and hence will be rejected.'
  },
  UNSTABLE_OFFSET_COMMIT: {
    id: 'UNSTABLE_OFFSET_COMMIT',
    code: 88,
    canRetry: true,
    message: 'There are unstable offsets that need to be cleared.'
  },
  THROTTLING_QUOTA_EXCEEDED: {
    id: 'THROTTLING_QUOTA_EXCEEDED',
    code: 89,
    canRetry: true,
    message: 'The throttling quota has been exceeded.'
  },
  PRODUCER_FENCED: {
    id: 'PRODUCER_FENCED',
    code: 90,
    canRetry: false,
    message: 'There is a newer producer with the same transactionalId which fences the current one.'
  },
  RESOURCE_NOT_FOUND: {
    id: 'RESOURCE_NOT_FOUND',
    code: 91,
    canRetry: false,
    message: 'A request illegally referred to a resource that does not exist.'
  },
  DUPLICATE_RESOURCE: {
    id: 'DUPLICATE_RESOURCE',
    code: 92,
    canRetry: false,
    message: 'A request illegally referred to the same resource twice.'
  },
  UNACCEPTABLE_CREDENTIAL: {
    id: 'UNACCEPTABLE_CREDENTIAL',
    code: 93,
    canRetry: false,
    message: 'Requested credential would not meet criteria for acceptability.'
  },
  INCONSISTENT_VOTER_SET: {
    id: 'INCONSISTENT_VOTER_SET',
    code: 94,
    canRetry: false,
    message:
      'Indicates that the either the sender or recipient of a voter-only request is not one of the expected voters.'
  },
  INVALID_UPDATE_VERSION: {
    id: 'INVALID_UPDATE_VERSION',
    code: 95,
    canRetry: false,
    message: 'The given update version was invalid.'
  },
  FEATURE_UPDATE_FAILED: {
    id: 'FEATURE_UPDATE_FAILED',
    code: 96,
    canRetry: false,
    message: 'Unable to update finalized features due to an unexpected server error.'
  },
  PRINCIPAL_DESERIALIZATION_FAILURE: {
    id: 'PRINCIPAL_DESERIALIZATION_FAILURE',
    code: 97,
    canRetry: false,
    message:
      'Request principal deserialization failed during forwarding. This indicates an internal error on the broker cluster security setup.'
  },
  SNAPSHOT_NOT_FOUND: {
    id: 'SNAPSHOT_NOT_FOUND',
    code: 98,
    canRetry: false,
    message: 'Requested snapshot was not found.'
  },
  POSITION_OUT_OF_RANGE: {
    id: 'POSITION_OUT_OF_RANGE',
    code: 99,
    canRetry: false,
    message: 'Requested position is not greater than or equal to zero, and less than the size of the snapshot.'
  },
  UNKNOWN_TOPIC_ID: {
    id: 'UNKNOWN_TOPIC_ID',
    code: 100,
    canRetry: true,
    message: 'This server does not host this topic ID.'
  },
  DUPLICATE_BROKER_REGISTRATION: {
    id: 'DUPLICATE_BROKER_REGISTRATION',
    code: 101,
    canRetry: false,
    message: 'This broker ID is already in use.'
  },
  BROKER_ID_NOT_REGISTERED: {
    id: 'BROKER_ID_NOT_REGISTERED',
    code: 102,
    canRetry: false,
    message: 'The given broker ID was not registered.'
  },
  INCONSISTENT_TOPIC_ID: {
    id: 'INCONSISTENT_TOPIC_ID',
    code: 103,
    canRetry: true,
    message: "The log's topic ID did not match the topic ID in the request."
  },
  INCONSISTENT_CLUSTER_ID: {
    id: 'INCONSISTENT_CLUSTER_ID',
    code: 104,
    canRetry: false,
    message: 'The clusterId in the request does not match that found on the server.'
  },
  TRANSACTIONAL_ID_NOT_FOUND: {
    id: 'TRANSACTIONAL_ID_NOT_FOUND',
    code: 105,
    canRetry: false,
    message: 'The transactionalId could not be found.'
  },
  FETCH_SESSION_TOPIC_ID_ERROR: {
    id: 'FETCH_SESSION_TOPIC_ID_ERROR',
    code: 106,
    canRetry: true,
    message: 'The fetch session encountered inconsistent topic ID usage.'
  },
  INELIGIBLE_REPLICA: {
    id: 'INELIGIBLE_REPLICA',
    code: 107,
    canRetry: false,
    message: 'The new ISR contains at least one ineligible replica.'
  },
  NEW_LEADER_ELECTED: {
    id: 'NEW_LEADER_ELECTED',
    code: 108,
    canRetry: false,
    message: 'The AlterPartition request successfully updated the partition state but the leader has changed.'
  },
  OFFSET_MOVED_TO_TIERED_STORAGE: {
    id: 'OFFSET_MOVED_TO_TIERED_STORAGE',
    code: 109,
    canRetry: false,
    message: 'The requested offset is moved to tiered storage.'
  },
  FENCED_MEMBER_EPOCH: {
    id: 'FENCED_MEMBER_EPOCH',
    code: 110,
    canRetry: false,
    message:
      'The member epoch is fenced by the group coordinator. The member must abandon all its partitions and rejoin.'
  },
  UNRELEASED_INSTANCE_ID: {
    id: 'UNRELEASED_INSTANCE_ID',
    code: 111,
    canRetry: false,
    message: 'The instance ID is still used by another member in the consumer group. That member must leave first.'
  },
  UNSUPPORTED_ASSIGNOR: {
    id: 'UNSUPPORTED_ASSIGNOR',
    code: 112,
    canRetry: false,
    message: 'The assignor or its version range is not supported by the consumer group.'
  },
  STALE_MEMBER_EPOCH: {
    id: 'STALE_MEMBER_EPOCH',
    code: 113,
    canRetry: false,
    message:
      'The member epoch is stale. The member must retry after receiving its updated member epoch via the ConsumerGroupHeartbeat API.'
  },
  MISMATCHED_ENDPOINT_TYPE: {
    id: 'MISMATCHED_ENDPOINT_TYPE',
    code: 114,
    canRetry: false,
    message: 'The request was sent to an endpoint of the wrong type.'
  },
  UNSUPPORTED_ENDPOINT_TYPE: {
    id: 'UNSUPPORTED_ENDPOINT_TYPE',
    code: 115,
    canRetry: false,
    message: 'This endpoint type is not supported yet.'
  },
  UNKNOWN_CONTROLLER_ID: {
    id: 'UNKNOWN_CONTROLLER_ID',
    code: 116,
    canRetry: false,
    message: 'This controller ID is not known.'
  },
  UNKNOWN_SUBSCRIPTION_ID: {
    id: 'UNKNOWN_SUBSCRIPTION_ID',
    code: 117,
    canRetry: false,
    message: 'Client sent a push telemetry request with an invalid or outdated subscription ID.'
  },
  TELEMETRY_TOO_LARGE: {
    id: 'TELEMETRY_TOO_LARGE',
    code: 118,
    canRetry: false,
    message: 'Client sent a push telemetry request larger than the maximum size the broker will accept.'
  },
  INVALID_REGISTRATION: {
    id: 'INVALID_REGISTRATION',
    code: 119,
    canRetry: false,
    message: 'The controller has considered the broker registration to be invalid.'
  },
  TRANSACTION_ABORTABLE: {
    id: 'TRANSACTION_ABORTABLE',
    code: 120,
    canRetry: false,
    message:
      'The server encountered an error with the transaction. The client can abort the transaction to continue using this transactional ID.'
  },
  INVALID_RECORD_STATE: {
    id: 'INVALID_RECORD_STATE',
    code: 121,
    canRetry: false,
    message: 'The record state is invalid. The acknowledgement of delivery could not be completed.'
  },
  SHARE_SESSION_NOT_FOUND: {
    id: 'SHARE_SESSION_NOT_FOUND',
    code: 122,
    canRetry: true,
    message: 'The share session was not found.'
  },
  INVALID_SHARE_SESSION_EPOCH: {
    id: 'INVALID_SHARE_SESSION_EPOCH',
    code: 123,
    canRetry: true,
    message: 'The share session epoch is invalid.'
  },
  FENCED_STATE_EPOCH: {
    id: 'FENCED_STATE_EPOCH',
    code: 124,
    canRetry: false,
    message: 'The share coordinator rejected the request because the share-group state epoch did not match.'
  },
  INVALID_VOTER_KEY: {
    id: 'INVALID_VOTER_KEY',
    code: 125,
    canRetry: false,
    message: "The voter key doesn't match the receiving replica's key."
  },
  DUPLICATE_VOTER: {
    id: 'DUPLICATE_VOTER',
    code: 126,
    canRetry: false,
    message: 'The voter is already part of the set of voters.'
  },
  VOTER_NOT_FOUND: {
    id: 'VOTER_NOT_FOUND',
    code: 127,
    canRetry: false,
    message: 'The voter is not part of the set of voters.'
  }
}
