services:
  kafka:
    image: bitnami/kafka:${KAFKA_VERSION}
    ports:
      - '9092:9092' # PLAIN TEXT
      - '9095:9095' # SASL
      - '9098:9098' # SSL
    volumes:
      - './data/jaas/jaas.conf:/opt/bitnami/kafka/config/kafka_jaas.conf'
      - './data/ssl/server.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
      - './data/ssl/server.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro'
    environment:
      # General options
      _JAVA_OPTIONS: '-XX:UseSVE=0' #Needed for Docker on Apple Silicon
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_ENABLE_KRAFT: 'yes'
      KAFKA_KRAFT_CLUSTER_ID: 'abcdefghijklmnopqrstuv'
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_CFG_NODE_ID: '1'
      # Ports configuration
      KAFKA_CFG_LISTENERS: 'PLAINTEXT://:9092,SASL_PLAINTEXT://:9095,SSL://:9098,CONTROLLER://:29092'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,SSL:SSL,CONTROLLER:PLAINTEXT'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092,SASL_PLAINTEXT://localhost:9095,SSL://localhost:9098'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@kafka:29092'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      # Replication options
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: '1'
      KAFKA_CFG_MIN_INSYNC_REPLICAS: '1'
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_CFG_TRANSACTION_PARTITION_VERIFICATION_ENABLE: 'false'
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: '1'
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
      # Consumer group options
      KAFKA_CFG_GROUP_COORDINATOR_REBALANCE_PROTOCOLS: 'classic,consumer'
      KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: '0'
      # SASL
      KAFKA_CLIENT_USERS: 'admin'
      KAFKA_CLIENT_PASSWORDS: 'admin'
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: 'PLAIN,SCRAM-SHA-256,SCRAM-SHA-512'
      KAFKA_CFG_SUPER_USERS: 'User:admin'
      KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'false'
      KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL: 'PLAIN'
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'PLAIN'
      # SSL
      KAFKA_CFG_SSL_KEYSTORE_PASSWORD: 12345678
      KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD: 12345678
      KAFKA_CFG_SSL_CLIENT_AUTH: required # This is to also enable mTLS
