/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class GSSAPI {
  constructor(kdc: string, realm: string)
  authenticateWithPassword(username: string, password: string): boolean
  authenticateWithKeytab(username: string, keytab: string): boolean
  step(service: string, input?: Buffer | undefined | null): StepResult
  wrap(data: Buffer): Buffer
  unwrap(data: Buffer): Buffer
}

export interface StepResult {
  output: Buffer
  completed: boolean
}
