[config]
  skip_core_tasks = true

[tasks.default]
  dependencies = ["build"]

[tasks.build]
  script = [
    "mkdir -p ../dist",
    "rm -rf ../dist/native.wasm",
    "RUSTFLAGS=\"-C target-feature=+simd128,+bulk-memory\" cargo build -Z unstable-options --target wasm32-unknown-unknown",
    "cp -a target/wasm32-unknown-unknown/debug/platformatic_kafka.wasm target/native-debug.wasm",
    "cp -a target/native-debug.wasm ../dist/native.wasm",
  ]

[tasks.release]
  script = [
    "mkdir -p ../dist",
    "rm -rf ../dist/native.wasm",
    "RUSTFLAGS=\"-C target-feature=+simd128,+bulk-memory\" cargo build --release -Z unstable-options --target wasm32-unknown-unknown",
    "cp -a target/wasm32-unknown-unknown/release/platformatic_kafka.wasm target/native-release.wasm",
    "cp -a target/native-release.wasm ../dist/native.wasm",
    "wasm-opt --enable-simd --enable-bulk-memory-opt -O3 -o ../dist/native.wasm ../dist/native.wasm",
  ]

[tasks.lint]
  command = "cargo"
  args    = ["clippy"]


[tasks.format]
  command = "cargo"
  args    = ["fmt"]

[tasks.clean]
  run_task = { name = ["cargo-clean", "dist-clean"] }


[tasks.cargo-clean]
  command = "cargo"
  args    = ["clean"]

[tasks.dist-clean]
  command = "rm"
  args    = ["-r", "-f", "native.wasm"]
